export const snacks = {
  section: "snacks",
  products: [
    {
      id: 1,
      category: "salty",
      image: "/images/products/snacks/chips.webp",
      name: "Potato Chips",
      old_price: 0,
      price: 1.99,
      search_words: ["potato chips", "chips"],
    },
    {
      id: 2,
      category: "sweet",
      image: "/images/products/snacks/chocolate-bar.webp",
      name: "Chocolate Bar",
      old_price: 0,
      price: 2.29,
      search_words: ["chocolate bar", "chocolate"],
    },
    {
      id: 3,
      category: "sweet",
      image: "/images/products/snacks/cookie.webp",
      name: "Cookies",
      old_price: 0,
      price: 2.09,
      search_words: ["cookies", "cookie"],
    },
    {
      id: 4,
      category: "salty",
      image: "/images/products/snacks/popcorn.webp",
      name: "Popcorn",
      old_price: 0,
      price: 1.99,
      search_words: ["popcorn"],
    },
    {
      id: 5,
      category: "salty",
      image: "/images/products/snacks/sandwich.webp",
      name: "Vegetarian Sandwich",
      old_price: 0,
      price: 1.89,
      search_words: ["vegetarian sandwich", "sandwich", "vegetarian"],
    },
    {
      id: 6,
      category: "drink",
      image: "/images/products/snacks/soft-drink.webp",
      name: "Soda",
      old_price: 0,
      price: 1.80,
      search_words: ["soda", "soft drink", "drink"],
    },
  ],
};

export const bakery = {
  section: "bakery",
  products: [
    {
      id: 1,
      category: "sweet",
      image: "/images/products/full-fridge/cinnamon-roll.webp",
      name: "Cinnamon Rolls",
      old_price: 0,
      price: 3.99,
      search_words: ["cinnamon rolls", "cinnamon", "rolls"],
    },
    {
      id: 2,
      category: "bread",
      image: "/images/products/full-fridge/garlic-bread.webp",
      name: "Garlic Bread",
      old_price: 0,
      price: 2.79,
      search_words: ["garlic bread", "garlic", "bread"],
    },
    {
      id: 3,
      category: "meat",
      image: "/images/secondcards/original-sausage.webp",
      name: "Original Sausage",
      old_price: 0,
      price: 2.09,
      search_words: ["original sausage", "sausage", "meat"],
    },
    {
      id: 4,
      category: "meat",
      image: "/images/products/full-fridge/prosciutto.webp",
      name: "Prosciutto Di Parma",
      old_price: 0,
      price: 4.99,
      search_words: ["prosciutto di parma", "prosciutto", "parma", "delli", "meat"],
    },
    {
      id: 5,
      category: "meat",
      image: "/images/products/full-fridge/salami.webp",
      name: "Spicy Salami",
      old_price: 0,
      price: 6.49,
      search_words: ["spicy salami", "salami", "meat"],
    },
    {
      id: 6,
      category: "parmesan",
      image: "/images/products/cheeses-and-dairy/parmesan.webp",
      name: "Parmesan Cheese",
      old_price: 0,
      price: 3.80,
      search_words: ["parmesan cheese", "parmesan", "cheese"],
    },
  ],
};

export const canneds = {
  section: "canneds",
  products: [
    {
      id: 1,
      category: "fish",
      image: "/images/products/canneds/tuna.webp",
      name: "Canned Tuna",
      old_price: 0,
      price: 4.99,
      search_words: ["canned tuna", "fish", "canned"],
    },
    {
      id: 2,
      category: "vegetable",
      image: "/images/products/canneds/tomato-sauce.webp",
      name: "Tomato Sauce",
      old_price: 1.36,
      price: 0.96,
      search_words: ["tomato sauce", "canned"],
    },
    {
      id: 3,
      category: "vegetable",
      image: "/images/products/canneds/beans.webp",
      name: "Canned Beans",
      old_price: 0,
      price: 2.96,
      search_words: ["canned beans", "canned", "beans", "bean", "canned bean"],
    },
    {
      id: 4,
      category: "fish",
      image: "/images/products/canneds/sardines.webp",
      name: "Canned Sardines",
      old_price: 0,
      price: 2.96,
      search_words: ["canned sardines", "canned", "sardine", "canned sardine"],
    },
    {
      id: 5,
      category: "fruit",
      image: "/images/products/canneds/peach.webp",
      name: "Canned Peach",
      old_price: 0,
      price: 3.4,
      search_words: ["canned peach", "canned", "peach", "peaches"],
    },
    {
      id: 6,
      category: "fruit",
      image: "/images/products/canneds/pineapple.webp",
      name: "Canned Pineapple",
      old_price: 0,
      price: 3.6,
      search_words: ["canned pineapple", "canned", "pineapple", "pineapples"],
    },
  ],
};

export const cheesesAndDairy = {
  section: "cheeses-and-dairy",
  products: [
    {
      id: 1,
      category: "american",
      image: "/images/products/cheeses-and-dairy/cheese-slice.webp",
      name: "Cheese Slices",
      old_price: 0,
      price: 4.89,
      search_words: ["cheese slices", "cheese"],
    },
    {
      id: 2,
      category: "parmesan",
      image: "/images/products/cheeses-and-dairy/parmesan.webp",
      name: "Parmesan Cheese",
      old_price: 0,
      price: 3.8,
      search_words: ["parmesan cheese", "parmesan", "cheese"],
    },
    {
      id: 3,
      category: "mozzarella",
      image: "/images/products/cheeses-and-dairy/mozzarella.webp",
      name: "Mozzarella",
      old_price: 0,
      price: 2.19,
      search_words: ["mozzarella", "cheese"],
    },
    {
      id: 4,
      category: "american",
      image: "/images/products/cheeses-and-dairy/cream-cheese.webp",
      name: "Cream Cheese",
      old_price: 0,
      price: 2.45,
      search_words: ["cream cheese", "cheese"],
    },
    {
      id: 5,
      category: "gorgonzola",
      image: "/images/products/cheeses-and-dairy/gorgonzola.webp",
      name: "Gorgonzola",
      old_price: 0,
      price: 4.5,
      search_words: ["gorgonzola", "cheese"],
    },
    {
      id: 6,
      category: "gouda",
      image: "/images/products/cheeses-and-dairy/gouda.webp",
      name: "Gouda Cheese",
      old_price: 0,
      price: 3.75,
      search_words: ["gouda", "gouda cheese", "cheese"],
    },
  ],
};

export const dietary = {
  section: "dietary",
  products: [
    {
      id: 1,
      category: "protein",
      image: "/images/products/dietary/protein.webp",
      name: "Protein Powder",
      old_price: 0,
      price: 31.9,
      search_words: ["protein powder", "protein", "powder", "supplement", "gym"],
    },
    {
      id: 2,
      category: "juice",
      image: "/images/products/dietary/detox.webp",
      name: "Detox Juice",
      old_price: 0,
      price: 5.99,
      search_words: ["detox juice", "detox", "juice"],
    },
    {
      id: 3,
      category: "vitamin",
      image: "/images/products/dietary/vitamin-d3.webp",
      name: "Vitamin D3",
      old_price: 0,
      price: 8.99,
      search_words: ["vitamin d3", "vitamin"],
    },
    {
      id: 4,
      category: "vitamin",
      image: "/images/products/dietary/vitamin-d.webp",
      name: "Vitamin D",
      old_price: 0,
      price: 7.99,
      search_words: ["vitamin d", "vitamin"],
    },
    {
      id: 5,
      category: "vitamin",
      image: "/images/products/dietary/vitamin-b.webp",
      name: "Vitamin B",
      old_price: 0,
      price: 8.99,
      search_words: ["vitamin b", "vitamin"],
    },
    {
      id: 6,
      category: "vitamin",
      image: "/images/products/dietary/vitamin-c.webp",
      name: "Vitamin C",
      old_price: 0,
      price: 7.99,
      search_words: ["vitamin c", "vitamin"],
    },
  ],
};

export const eggs = {
  section: "eggs",
  products: [
    {
      id: 1,
      category: "chicken",
      image: "/images/products/eggs/brown-eggs.webp",
      name: "Large Brown Eggs",
      old_price: 0,
      price: 3.59,
      search_words: ["large brown eggs", "brown eggs", "eggs", "egg"],
    },
    {
      id: 2,
      category: "chicken",
      image: "/images/products/eggs/eggs.webp",
      name: "Large White Eggs",
      old_price: 0,
      price: 3.99,
      search_words: ["large white eggs", "white eggs", "eggs", "egg"],
    },
    {
      id: 3,
      category: "quail",
      image: "/images/products/eggs/quail-eggs.webp",
      name: "Quail Eggs",
      old_price: 0,
      price: 2.99,
      search_words: ["quail eggs", "eggs", "egg"],
    },
    {
      id: 4,
      category: "duck",
      image: "/images/products/eggs/duck-eggs.webp",
      name: "Duck Eggs",
      old_price: 0,
      price: 5.99,
      search_words: ["duck eggs", "eggs", "egg"],
    },
    {
      id: 2,
      category: "turkey",
      image: "/images/products/eggs/turkey-egg.webp",
      name: "Turkey Egg",
      old_price: 0,
      price: 6.99,
      search_words: ["turkey egg", "eggs", "egg"],
    },
    {
      id: 2,
      category: "ostrich",
      image: "/images/products/eggs/ostrich-egg.webp",
      name: "Ostrich Egg",
      old_price: 0,
      price: 9.99,
      search_words: ["ostrich egg", "eggs", "egg"],
    },
  ],
};

export const fishery = {
  section: "fishery",
  products: [
    {
      id: 1,
      category: "cartilaginous",
      image: "/images/products/fishery/atlantic-salmon.webp",
      name: "Atlantic Salmon",
      old_price: 0,
      price: 9.99,
      search_words: ["atlantic salmon", "salmon", "fish"],
    },
    {
      id: 2,
      category: "cartilaginous",
      image: "/images/products/fishery/tuna.webp",
      name: "Light Tuna",
      old_price: 0,
      price: 6.99,
      search_words: ["light tuna", "tuna", "fish"],
    },
    {
      id: 3,
      category: "cartilaginous",
      image: "/images/products/fishery/tilapia.webp",
      name: "Tilapia",
      old_price: 0,
      price: 5.08,
      search_words: ["tilapia", "fish"],
    },
    {
      id: 4,
      category: "cartilaginous",
      image: "/images/products/fishery/herring.webp",
      name: "Herring",
      old_price: 0,
      price: 4.09,
      search_words: ["herring", "fish"],
    },
    {
      id: 5,
      category: "cartilaginous",
      image: "/images/products/fishery/sardines.webp",
      name: "Sardines",
      old_price: 0,
      price: 2.19,
      search_words: ["sardines", "fish"],
    },
    {
      id: 6,
      category: "cartilaginous",
      image: "/images/products/fishery/yellowfin-tuna.webp",
      name: "Yellowfin Tuna",
      old_price: 0,
      price: 6.65,
      search_words: ["yellowfin tuna", "fish"],
    },
  ],
};

export const frozen = {
  section: "frozen",
  products: [
    {
      id: 1,
      category: "sweet",
      image: "/images/products/frozen/ice-cream.webp",
      name: "Napolitano Gelati",
      old_price: 0,
      price: 4.99,
      search_words: ["napolitano gelati", "napolitano", "ice", "cream", "gelato", "gelati"],
    },
    {
      id: 2,
      category: "sweet",
      image: "/images/products/frozen/peach-yogurt.webp",
      name: "Peach Yogurt",
      old_price: 0,
      price: 0.65,
      search_words: ["peach yogurt", "peach", "yogurt"],
    },
    {
      id: 3,
      category: "meat",
      image: "/images/products/frozen/chicken-breast.webp",
      name: "Chicken Breast",
      old_price: 12.98,
      price: 11.08,
      search_words: ["chicken breast", "meat", "chicken"],
    },
    {
      id: 4,
      category: "sweet",
      image: "/images/products/frozen/yogurt.webp",
      name: "Strawberry Yogurt",
      old_price: 2.49,
      price: 2.09,
      search_words: ["strawberry yogurt", "yogurt"],
    },
    {
      id: 5,
      category: "meat",
      image: "/images/products/frozen/meatballs.webp",
      name: "Meatballs",
      old_price: 0,
      price: 7.19,
      search_words: ["meatballs", "meat"],
    },
    {
      id: 6,
      category: "vegetable",
      image: "/images/products/frozen/french-fries.webp",
      name: "French Fries",
      old_price: 0,
      price: 4.65,
      search_words: ["french fries", "fries", "potato"],
    },
  ],
};

export const cleaning = {
  section: "cleaning",
  products: [
    {
      id: 1,
      category: "utensils",
      image: "/images/products/cleaning/antiseptic.webp",
      name: "Antiseptic",
      old_price: 0,
      price: 2.65,
      search_words: ["antiseptic", "alcohol"],
    },
    {
      id: 2,
      category: "utensils",
      image: "/images/products/cleaning/broom.webp",
      name: "Broom",
      old_price: 0,
      price: 9.90,
      search_words: ["broom"],
    },
    {
      id: 3,
      category: "utensils",
      image: "/images/products/cleaning/bucket.webp",
      name: "Bucket",
      old_price: 0,
      price: 3.1,
      search_words: ["bucket"],
    },
    {
      id: 4,
      category: "utensils",
      image: "/images/products/cleaning/dustpan.webp",
      name: "Dustpan",
      old_price: 0,
      price: 2.45,
      search_words: ["dustpan"],
    },
    {
      id: 5,
      category: "utensils",
      image: "/images/products/cleaning/floor-cloth.webp",
      name: "Floor Cloth",
      old_price: 0,
      price: 0.69,
      search_words: ["floor cloth", "cloth"],
    },
    {
      id: 6,
      category: "utensils",
      image: "/images/products/cleaning/garbage-bag.webp",
      name: "Garbage Bag",
      old_price: 0,
      price: 0.19,
      search_words: ["garbage bag", "bag", "plastic"],
    },
    {
      id: 7,
      category: "utensils",
      image: "/images/products/cleaning/garbage.webp",
      name: "Trash Can",
      old_price: 0,
      price: 7.55,
      search_words: ["trash can", "trash", "bin", "can"],
    },
    {
      id: 8,
      category: "utensils",
      image: "/images/products/cleaning/mop.webp",
      name: "Mop",
      old_price: 0,
      price: 12.29,
      search_words: ["mop"],
    },
    {
      id: 9,
      category: "soap",
      image: "/images/products/cleaning/soap.webp",
      name: "Soap",
      old_price: 0,
      price: 0.61,
      search_words: ["soap"],
    },
    {
      id: 10,
      category: "utensils",
      image: "/images/products/cleaning/sponge.webp",
      name: "Sponge",
      old_price: 0,
      price: 0.85,
      search_words: ["sponge"],
    },
    {
      id: 11,
      category: "utensils",
      image: "/images/products/cleaning/squeegee.webp",
      name: "Squeegee",
      old_price: 0,
      price: 8.9,
      search_words: ["squeegee"],
    },
    {
      id: 12,
      category: "utensils",
      image: "/images/products/cleaning/vacuum.webp",
      name: "Vacuum",
      old_price: 0,
      price: 95.99,
      search_words: ["vacuum"],
    },
  ],
};

export const essentials = {
  section: "essentials",
  products: [
    {
      id: 1,
      category: "seasoning",
      image: "/images/products/essentials/salt2.webp",
      name: "Iodized Salt",
      old_price: 0,
      price: 0.49,
      search_words: ["iodized salt", "salt", "iodized"],
    },
    {
      id: 2,
      category: "seasoning",
      image: "/images/products/essentials/sugar2.webp",
      name: "Granulated Sugar",
      old_price: 0,
      price: 2.49,
      search_words: ["granulated sugar", "granulated", "sugar"],
    },
    {
      id: 3,
      category: "flour",
      image: "/images/products/essentials/flour2.webp",
      name: "All Purpose Flour",
      old_price: 0,
      price: 1.17,
      search_words: ["all purpose flour", "flour"],
    },
    {
      id: 4,
      category: "oil",
      image: "/images/products/essentials/oil.webp",
      name: "Vegetable Oil",
      old_price: 0,
      price: 3.75,
      search_words: ["vegetable oil", "vegetable", "oil"],
    },
    {
      id: 5,
      category: "bean",
      image: "/images/products/essentials/bean.webp",
      name: "Cannellini Beans",
      old_price: 0,
      price: 2.69,
      search_words: ["cannellini beans", "cannellini", "bean", "beans"],
    },
    {
      id: 6,
      category: "rice",
      image: "/images/products/essentials/rice.webp",
      name: "Enriched Long Rice",
      old_price: 0,
      price: 2.29,
      search_words: ["enriched long rice", "rice"],
    },
    {
      id: 7,
      category: "utensil",
      image: "/images/products/essentials/paper-towel.webp",
      name: "Paper Towel",
      old_price: 0,
      price: 6.55,
      search_words: ["paper towel", "towel", "paper"],
    },
    {
      id: 8,
      category: "oil",
      image: "/images/products/essentials/olive-oil.webp",
      name: "Olive Oil",
      old_price: 0,
      price: 3.4,
      search_words: ["olive oil", "olive", "oil"],
    },
    {
      id: 9,
      category: "utensil",
      image: "/images/products/essentials/toothpick.webp",
      name: "Toothpick",
      old_price: 0,
      price: 2.44,
      search_words: ["toothpick", "teethpick"],
    },
    {
      id: 10,
      category: "water",
      image: "/images/products/essentials/water.webp",
      name: "Bottled Water",
      old_price: 0,
      price: 0.65,
      search_words: ["bottled water", "bottled", "water"],
    },
    {
      id: 11,
      category: "coffee",
      image: "/images/products/essentials/coffee-beans.webp",
      name: "Coffee",
      old_price: 0,
      price: 2.89,
      search_words: ["coffee"],
    },
    {
      id: 12,
      category: "egg",
      image: "/images/products/essentials/egg.webp",
      name: "Large Brown Eggs",
      old_price: 0,
      price: 3.59,
      search_words: ["large brown eggs", "brown", "eggs", "egg"],
    },
  ],
};

export const fullFridge = {
  section: "full-fridge",
  products: [
    {
      id: 1,
      category: "bread",
      image: "/images/products/full-fridge/garlic-bread.webp",
      name: "Garlic Bread",
      old_price: 0,
      price: 2.79,
      search_words: ["garlic bread", "garlic", "bread"],
    },
    {
      id: 2,
      category: "meat",
      image: "/images/products/full-fridge/ham.webp",
      name: "Black Forest Ham",
      old_price: 0,
      price: 3.19,
      search_words: ["black forest ham", "ham", "meat"],
    },
    {
      id: 3,
      category: "meat",
      image: "/images/products/full-fridge/ravioli.webp",
      name: "Chicken & Prosciutto Ravioli",
      old_price: 0,
      price: 3.49,
      search_words: ["chicken and prosciutto ravioli", "ravioli", "chicken", "prosciutto"],
    },
    {
      id: 4,
      category: "sweet",
      image: "/images/products/full-fridge/cinnamon-roll.webp",
      name: "Cinnamon Rolls",
      old_price: 0,
      price: 3.99,
      search_words: ["cinnamon rolls", "cinnamon", "rolls"],
    },
    {
      id: 5,
      category: "sweet",
      image: "/images/products/full-fridge/ice-cream.webp",
      name: "Napolitano Gelati",
      old_price: 0,
      price: 4.99,
      search_words: ["napolitano gelati", "napolitano", "ice", "cream", "gelato", "gelati"],
    },
    {
      id: 6,
      category: "meat",
      image: "/images/products/full-fridge/turkey.webp",
      name: "Honey Smoked Turkey",
      old_price: 0,
      price: 13.49,
      search_words: ["honey smoked turkey", "meat", "turkey"],
    },
    {
      id: 7,
      category: "sauce",
      image: "/images/products/full-fridge/salsa.webp",
      name: "Medium Salsa",
      old_price: 0,
      price: 2.55,
      search_words: ["medium sala", "salsa"],
    },
    {
      id: 8,
      category: "meat",
      image: "/images/products/full-fridge/prosciutto.webp",
      name: "Prosciutto Di Parma",
      old_price: 0,
      price: 4.99,
      search_words: ["prosciutto di parma", "prosciutto", "parma", "meat"],
    },
    {
      id: 9,
      category: "milk",
      image: "/images/products/full-fridge/milk.webp",
      name: "Organic Vanilla Soymilk",
      old_price: 0,
      price: 2.44,
      search_words: ["organic vanilla soymilk", "milk", "soy", "soymilk"],
    },
    {
      id: 10,
      category: "sweet",
      image: "/images/products/full-fridge/peach-yogurt.webp",
      name: "Peach Yogurt",
      old_price: 0,
      price: 0.65,
      search_words: ["peach yogurt", "peach", "yogurt"],
    },
    {
      id: 11,
      category: "pasta",
      image: "/images/products/full-fridge/pizza.webp",
      name: "Pepperoni Pizza",
      old_price: 0,
      price: 6.89,
      search_words: ["pepperoni pizza", "pepperoni", "pizza"],
    },
    {
      id: 12,
      category: "meat",
      image: "/images/products/full-fridge/salami.webp",
      name: "Spicy Salami",
      old_price: 0,
      price: 6.49,
      search_words: ["spicy salami", "spice", "salami"],
    },
  ],
};

export const beverages = {
  section: "beverages",
  products: [
    {
      id: 1,
      category: "juice",
      image: "/images/products/beverages/coconut-water.webp",
      name: "Coconut Juice",
      old_price: 0,
      price: 2.09,
      search_words: ["coconut juice", "juice"],
    },
    {
      id: 2,
      category: "juice",
      image: "/images/products/beverages/grapes-juice.webp",
      name: "100% Grape Juice",
      old_price: 0,
      price: 2.79,
      search_words: ["grape juice", "juice"],
    },
    {
      id: 3,
      category: "juice",
      image: "/images/products/beverages/fruit-punch.webp",
      name: "Fruit Punch Juice",
      old_price: 0,
      price: 1.59,
      search_words: ["fruit punch juice", "fruit", "punch", "juice"],
    },
    {
      id: 4,
      category: "juice",
      image: "/images/products/beverages/green-lemon-juice.webp",
      name: "Green Lemon Juice",
      old_price: 0,
      price: 1.15,
      search_words: ["green lemon juice", "juice"],
    },
    {
      id: 5,
      category: "juice",
      image: "/images/products/beverages/mango-juice.webp",
      name: "Mango Passion 100% Juice",
      old_price: 0,
      price: 3.19,
      search_words: ["mango passion juice", "mango", "passion", "juice"],
    },
    {
      id: 6,
      category: "juice",
      image: "/images/products/beverages/strawberry-juice.webp",
      name: "Strawberry Juice",
      old_price: 0,
      price: 1.39,
      search_words: ["strawberry juice", "juice"],
    },
    {
      id: 7,
      category: "juice",
      image: "/images/products/beverages/mint-tea.webp",
      name: "Mint Green Tea",
      old_price: 0,
      price: 1.38,
      search_words: ["mint green tea", "mint tea", "tea"],
    },
    {
      id: 8,
      category: "juice",
      image: "/images/products/beverages/orange-juice.webp",
      name: "Orange Pulp Free",
      old_price: 0,
      price: 3.98,
      search_words: ["orange pulp free", "orange juice", "juice"],
    },
    {
      id: 9,
      category: "juice",
      image: "/images/products/beverages/apple-juice.webp",
      name: "Organic Apple Juice",
      old_price: 0,
      price: 2.49,
      search_words: ["organic apple juice", "apple juice", "juice", "apple"],
    },
    {
      id: 10,
      category: "juice",
      image: "/images/products/beverages/black-teas.webp",
      name: "Sweet Black Tea",
      old_price: 0,
      price: 0.99,
      search_words: ["sweet black tea", "black tea", "tea"],
    },
    {
      id: 11,
      category: "juice",
      image: "/images/products/beverages/vegetable-juice.webp",
      name: "Vegetable Juice",
      old_price: 0,
      price: 3.98,
      search_words: ["vegetable juice", "juice"],
    },
    {
      id: 12,
      category: "juice",
      image: "/images/products/beverages/watermelon-juice.webp",
      name: "Watermelon Juice",
      old_price: 0,
      price: 3.19,
      search_words: ["watermelon juice", "juice"],
    },
  ],
};

export const fruits = {
  section: "fruits",
  products: [
    {
      id: 1,
      category: "fruit",
      image: "/images/products/fruits/avocados.webp",
      name: "Avocado",
      old_price: 1.99,
      price: 1.69,
      search_words: ["fruit", "fruits", "avocado", "avocados"],
    },
    {
      id: 2,
      category: "fruit",
      image: "/images/products/fruits/apples.webp",
      name: "Fuji Apples",
      old_price: 2.69,
      price: 2.39,
      search_words: ["fuji apples", "fruit", "fruits", "apple", "apples"],
    },
    {
      id: 3,
      category: "fruit",
      image: "/images/products/fruits/lemons.webp",
      name: "Lemons",
      old_price: 0.68,
      price: 0.48,
      search_words: ["lemons", "fruit", "lemon", "fruits"],
    },
    {
      id: 4,
      category: "fruit",
      image: "/images/products/fruits/pineapple.webp",
      name: "Pineapple",
      old_price: 4.39,
      price: 4.09,
      search_words: ["pineapple", "pineapples", "fruit", "fruits"],
    },
    {
      id: 5,
      category: "fruit",
      image: "/images/products/fruits/watermelon.webp",
      name: "Watermelon",
      old_price: 5.69,
      price: 5.19,
      search_words: ["watermelon", "fruit", "fruits"],
    },
    {
      id: 2,
      category: "fruit",
      image: "/images/products/fruits/strawberry.webp",
      name: "Strawberry",
      old_price: 1.28,
      price: 0.88,
      search_words: ["strawberry", "fruit", "fruits"],
    },
  ],
};

export const offers = {
  section: "offers",
  products: [
    {
      id: 1,
      category: "juice",
      image: "/images/products/offers/lemon-juice.webp",
      name: "100% Lemon Juice",
      old_price: 2.39,
      price: 2.09,
      search_words: ["100% lemon juice", "lemon juice", "lemon", "juice"],
    },
    {
      id: 2,
      category: "fruit",
      image: "/images/products/offers/avocados.webp",
      name: "Avocado",
      old_price: 1.99,
      price: 1.69,
      search_words: ["avocado", "fruit", "avocados", "fruits"],
    },
    {
      id: 3,
      category: "meat",
      image: "/images/products/offers/ribs.webp",
      name: "Baby Back Ribs",
      old_price: 2.89,
      price: 2.59,
      search_words: ["baby back ribs", "ribs", "baby ribs", "meat"],
    },
    {
      id: 4,
      category: "syrup",
      image: "/images/products/offers/maple-syrup.webp",
      name: "Butter Syrup",
      old_price: 2.09,
      price: 1.79,
      search_words: ["butter syrup", "butter", "syrup"],
    },
    {
      id: 5,
      category: "meat",
      image: "/images/products/offers/chicken-breast.webp",
      name: "Chicken Breast",
      old_price: 12.98,
      price: 11.08,
      search_words: ["chicken breast", "meat", "chicken"],
    },
    {
      id: 6,
      category: "pet",
      image: "/images/products/offers/dog-treat.webp",
      name: "Dog Treats Bacon",
      old_price: 5.29,
      price: 4.79,
      search_words: ["dog treats bacon", "dog treats", "treats", "dog", "pet"],
    },
    {
      id: 7,
      category: "meat",
      image: "/images/products/offers/bacons.webp",
      name: "Hickory Smoked Bacon",
      old_price: 3.89,
      price: 3.39,
      search_words: ["hickory smoked bacon", "smoked bacon", "bacon", "meat"],
    },
    {
      id: 8,
      category: "meat",
      image: "/images/products/offers/burger-patty.webp",
      name: "Ground Beef Patties",
      old_price: 4.24,
      price: 3.89,
      search_words: [
        "ground beef patties",
        "beef",
        "patties",
        "meat",
        "hamburguer",
        "burger",
      ],
    },
    {
      id: 9,
      category: "fruit",
      image: "/images/products/offers/apples.webp",
      name: "Fuji Apples",
      old_price: 2.69,
      price: 2.39,
      search_words: ["fuji apples", "apples", "apple", "fruit", "fruits"],
    },
    {
      id: 10,
      category: "fruit",
      image: "/images/products/offers/lemons.webp",
      name: "Lemons",
      old_price: 0.68,
      price: 0.48,
      search_words: ["lemons", "fruit", "lemon", "fruits"],
    },
    {
      id: 11,
      category: "pasta",
      image: "/images/products/offers/macaroni.webp",
      name: "Macaroni & Beef",
      old_price: 0.97,
      price: 0.57,
      search_words: ["macaroni & beef", "macaroni and beef", "macaroni", "pasta"],
    },
    {
      id: 12,
      category: "cake",
      image: "/images/products/offers/cheesecakes.webp",
      name: "New York Cheese Cake",
      old_price: 12.98,
      price: 10.08,
      search_words: ["new york cheese cake", "cheese", "cake", "cheese cake"],
    },
    {
      id: 13,
      category: "fruit",
      image: "/images/products/offers/pineapple.webp",
      name: "Pineapple",
      old_price: 4.39,
      price: 4.09,
      search_words: ["pineapple", "pineapples", "fruit", "fruits"],
    },
    {
      id: 14,
      category: "fruit",
      image: "/images/products/offers/watermelon.webp",
      name: "Watermelon",
      old_price: 5.69,
      price: 5.19,
      search_words: ["watermelon", "fruit", "fruits"],
    },
    {
      id: 15,
      category: "fruit",
      image: "/images/products/offers/yogurt.webp",
      name: "Strawberry Yogurt",
      old_price: 2.49,
      price: 2.09,
      search_words: ["strawberry yogurt", "strawberry", "yogurt"],
    },
    {
      id: 16,
      category: "broth",
      image: "/images/products/offers/broth.webp",
      name: "Beef Broth",
      old_price: 1.29,
      price: 0.99,
      search_words: ["beef broth", "beef", "broth", "broth"],
    },
    {
      id: 17,
      category: "fruit",
      image: "/images/products/offers/strawberry.webp",
      name: "Strawberry",
      old_price: 1.28,
      price: 0.88,
      search_words: ["strawberry", "fruit", "fruits"],
    },
    {
      id: 18,
      category: "sauce",
      image: "/images/products/offers/tomato-sauce.webp",
      name: "Tomato Sauce",
      old_price: 1.36,
      price: 0.96,
      search_words: ["tomato sauce", "tomato", "sauce", "tomatoes"],
    },
  ],
};

export const sweets = {
  section: "sweets",
  products: [
    {
      id: 1,
      category: "dough",
      image: "/images/products/sweets/donut.webp",
      name: "Donut",
      old_price: 0,
      price: 1.79,
      search_words: ["donut", "donuts"],
    },
    {
      id: 2,
      category: "chocolate",
      image: "/images/products/sweets/chocolate-bar.webp",
      name: "Chocolate Bar",
      old_price: 0,
      price: 2.29,
      search_words: ["chocolate bar", "chocolate"],
    },
    {
      id: 3,
      category: "chocolate",
      image: "/images/products/sweets/cookie.webp",
      name: "Cookies",
      old_price: 0,
      price: 2.09,
      search_words: ["cookies", "cookie"],
    },
    {
      id: 4,
      category: "dough",
      image: "/images/products/sweets/cinnamon-roll.webp",
      name: "Cinnamon Rolls",
      old_price: 0,
      price: 3.99,
      search_words: ["cinnamon rolls", "cinnamon", "rolls"],
    },
    {
      id: 5,
      category: "frozen",
      image: "/images/products/sweets/ice-cream.webp",
      name: "Napolitano Gelati",
      old_price: 0,
      price: 4.99,
      search_words: ["napolitano gelati", "napolitano", "ice", "cream", "gelato", "gelati"],
    },
    {
      id: 6,
      category: "frozen",
      image: "/images/products/sweets/peach-yogurt.webp",
      name: "Peach Yogurt",
      old_price: 0,
      price: 0.65,
      search_words: ["peach yogurt", "peach", "yogurt"],
    },
  ],
};

export const rotisserie = {
  section: "rotisserie",
  products: [
    {
      id: 1,
      category: "meat",
      image: "/images/products/rotisserie/chicken.webp",
      name: "Roasted Chicken",
      old_price: 0,
      price: 10.79,
      search_words: ["roasted chicken", "chicken", "meat"],
    },
    {
      id: 2,
      category: "meat",
      image: "/images/products/rotisserie/turkey.webp",
      name: "Honey Smoked Turkey",
      old_price: 0,
      price: 13.49,
      search_words: ["honey smoked turkey", "turkey", "smoked turkey", "meat"],
    },
    {
      id: 3,
      category: "meat",
      image: "/images/products/rotisserie/peking-duck.webp",
      name: "Roasted Duck",
      old_price: 0,
      price: 16.09,
      search_words: ["roasted duck", "duck", "meat"],
    },
    {
      id: 4,
      category: "meat",
      image: "/images/products/rotisserie/ribs.webp",
      name: "Baby Back Ribs",
      old_price: 2.89,
      price: 2.59,
      search_words: ["baby back ribs", "ribs", "meat"],
    },
    {
      id: 5,
      category: "vegetable",
      image: "/images/products/rotisserie/bell-pepper.webp",
      name: "Roasted Bell Pepper",
      old_price: 0,
      price: 2.99,
      search_words: ["roasted bell pepper", "bell pepper", "vegetable"],
    },
    {
      id: 6,
      category: "fruit",
      image: "/images/products/rotisserie/pineapple.webp",
      name: "Roasted Pineapple",
      old_price: 0,
      price: 4.65,
      search_words: ["roasted pineapple", "pineapple", "fruit"],
    },
  ],
};

export const seasoning = {
  section: "seasoning",
  products: [
    {
      id: 1,
      category: "powder",
      image: "/images/products/seasoning/salt2.webp",
      name: "Iodized Salt",
      old_price: 0,
      price: 0.49,
      search_words: ["iodized salt", "salt", "spices", "seasoning"],
    },
    {
      id: 2,
      category: "leaves",
      image: "/images/products/seasoning/basil.webp",
      name: "Basil",
      old_price: 0,
      price: 0.89,
      search_words: ["basil", "seasoning", "spices"],
    },
    {
      id: 3,
      category: "leaves",
      image: "/images/products/seasoning/oregano.webp",
      name: "Oregano",
      old_price: 0,
      price: 0.39,
      search_words: ["oregano", "seasoning", "spices"],
    },
    {
      id: 4,
      category: "powder",
      image: "/images/products/seasoning/paprika.webp",
      name: "Paprika",
      old_price: 0,
      price: 1.99,
      search_words: ["paprika", "seasoning", "spices"],
    },
    {
      id: 5,
      category: "powder",
      image: "/images/products/seasoning/pepper.webp",
      name: "Black Pepper",
      old_price: 0,
      price: 1.29,
      search_words: ["black pepper", "pepper", "seasoning", "spices"],
    },
    {
      id: 6,
      category: "powder",
      image: "/images/products/seasoning/turmeric.webp",
      name: "Turmeric",
      old_price: 0,
      price: 1.65,
      search_words: ["turmeric", "seasoning", "spices"],
    },
  ],
};

export const petshop = {
  section: "petshop",
  products: [
    {
      id: 1,
      category: "food",
      image: "/images/products/petshop/dog-food.webp",
      name: "Dog Food",
      old_price: 0,
      price: 11.49,
      search_words: ["dog food", "pet"],
    },
    {
      id: 2,
      category: "food",
      image: "/images/products/petshop/cat-food.webp",
      name: "Cat Food",
      old_price: 0,
      price: 8.89,
      search_words: ["cat food", "pet"],
    },
    {
      id: 3,
      category: "food",
      image: "/images/products/petshop/dog-treat.webp",
      name: "Dog Treats Bacon",
      old_price: 5.29,
      price: 4.79,
      search_words: ["dog treats bacon", "dog treat", "pet"],
    },
    {
      id: 4,
      category: "equipment",
      image: "/images/products/petshop/dog-bowl.webp",
      name: "Dog Bowl",
      old_price: 0,
      price: 3.29,
      search_words: ["dog bowl", "pet"],
    },
    {
      id: 5,
      category: "equipment",
      image: "/images/products/petshop/cat-bowl.webp",
      name: "Cat Bowl",
      old_price: 0,
      price: 2.29,
      search_words: ["cat bowl", "pet"],
    },
    {
      id: 6,
      category: "equipment",
      image: "/images/products/petshop/dog-house.webp",
      name: "Dog House",
      old_price: 0,
      price: 21.65,
      search_words: ["dog house", "pet"],
    },
  ],
};

export const catalog = [
  offers,
  fruits,
  beverages,
  fullFridge,
  essentials,
  cleaning,
	snacks,
	bakery,
	canneds,
	cheesesAndDairy,
	dietary,
	fishery,
	eggs,
	frozen,
	sweets,
	rotisserie,
	seasoning,
	petshop
];
